.PHONY: help tests env

help:
	@echo "Toptal Calorie Tracker Backend"
	@echo "### Commands ###"
	@echo "env"
	@echo "server"
	@echo "tests"

server:
	python create_app.py

tests:
	python -m nose -s tests/
